# Define services
services:

  # Database service using PostgreSQL image
  database:
    image: postgres:latest  # Use the latest PostgreSQL image from Docker Hub
    environment:
      POSTGRES_DB: twoguys  # Define the name of the database
      POSTGRES_USER: twoguysdb    # Define the username for accessing the database
      POSTGRES_PASSWORD: twoguys@3223  # Define the password for the user
    ports:
      - "5432:5432"  # Forward the container's port 5432 to the host machine's port 5432 for accessing PostgreSQL

  # Backend service
  backend:
    build: .  # Build the Docker image using the Dockerfile in the current directory
    ports:
      - "3200:5200"  # Forward the container's port 3333 to the host machine's port 3333 for accessing the backend service
    depends_on:
      - database  # Ensure that the backend service starts after the database service is up and running
    env_file:
      - .env  #